### ISSUE TITLE
Guest User can view Planet Detail Page/Component

### ISSUE THREAD

**Issue by foohonpie** [ImperialConflict/imperialconflict.com#10]
## API

`GET /planets/:planet_coordinates:`

example:

`/planets/89,8,45,2`

The dev API is now using an old prod snapshot with actual player data.

Example Response:

```
{
    "data": {
        "coordinates": {
            "label": "89,8,45,2",
            "galaxy_id": 89,
            "x": 8,
            "y": 45,
            "number": 2
        },
        "empire": {
            "id": 389582,
            "name": "Felix",
            "family": {
                "id": 7560
            }
        },
        "family": {
            "id": 7560
        },
        "bonuses": {
            "iron": "0.00",
            "food": "0.36",
            "octarine": "0.00",
            "endurium": "0.00"
        },
        "image_path": "/images/Planets/1_large.png",
        "system": {
            "coordinates": {
                "galaxy_id": 89,
                "x": 8,
                "y": 45,
                "label": "89,8,45"
            },
            "name": "Mitene"
        }
    }
}
```

## Design

See current page for reference:

https://imperialconflict.com/planets/view.php?galaxy=89&planet=8,45:2

Notes:
* The links can all be placeholders for now, as we don't yet have pages for systems, map, etc.
* We can ignore images for now, as we don't yet have a plan for handling image assets in general.
* We are now prepending the galaxy id onto planet/system coordinates.  For example, "The Mitene System (8,45)" will now become "The Mitene System (89,8,45)" and so on.
* The site page should be in the same coordinates format as the API: `/planets/89,8,45,2`
* We should plan for a reusable component for usage outside of just the planets page itself

### Desktop View

<img width="606" alt="imperial-conflict-guest-planet-detail-page-desktop" src="https://user-images.githubusercontent.com/674157/100949097-55a15880-34be-11eb-99b4-460d4c252cc2.png">

### Mobile View

<img width="386" alt="imperial-conflict-guest-planet-detail-page-mobile" src="https://user-images.githubusercontent.com/674157/100949105-5934df80-34be-11eb-9fd1-0f5e32767a60.png">

---

Please let me know if there are any questions!

**Comment by bpkennedy** [comment]
Awesome!  Acceptance Criteria questions below...

- [ ] What is the Max character limit for Empire or Family name?  If the system text is wide enough to wrap should I let the text wrap to a second line or text-ellipsize it with a tooltip on hover/touch?
- [ ] Should hyperlink styles also reflect when a link has been "visited" previously?  Or should it always be blue (except for hover possibly)?  I assume cursor:pointer css style over all hyperlinks as well, yes?
- [ ] Where are those icons coming from?
- [ ] Will planet images always be the same pixel height/width or are some larger than others?
- [ ] Is that 36 percent food directly from the API food bonus?  Will I need to round up/down for fractional percentages or will APi always return whole percentages?  UI suggestion: do you want me to color the percentage numbers depending on amount?  (i.e. less than 33 is red, between 33-66 white, 66+ is green)
- [ ] Are bonus percentages always positive or can they go negative?
- [ ] When a player has viewed a planet - should the client cache that planet's data and use it the next time they view it within the same browsing session?  Or should it always go ask the API when user views.  (Basically will planet data be changing frequently enough that caching isn't practical)?
- [ ] Should we display an inner loader for this component while the data for the planet is being fetched from the API?

**Comment by foohonpie** [comment]
> What is the Max character limit for Empire or Family name? If the system text is wide enough to wrap should I let the text wrap to a second line or text-ellipsize it with a tooltip on hover/touch?

Let's go with 20 for both Empire Name and System Name.  Family should always be 4 numbers.  How tough would it be to make it configurable?

> Should hyperlink styles also reflect when a link has been "visited" previously? Or should it always be blue (except for hover possibly)?

Yeah, let's show visited links as visited.

> I assume cursor:pointer css style over all hyperlinks as well, yes?

Yep!

> Where are those icons coming from?

They're more images, can ignore them for now.

> Will planet images always be the same pixel height/width or are some larger than others?

Let's plan for them always being 100x100.  We'll update the images as necessary.

>  Is that 36 percent food directly from the API food bonus? Will I need to round up/down for fractional percentages or will APi always return whole percentages? 

Yeah that's from the API food bonus.  They should always be 2 decimal places, and can be rounded up to a whole percentage.

> UI suggestion: do you want me to color the percentage numbers depending on amount? (i.e. less than 33 is red, between 33-66 white, 66+ is green)

Great idea!  Let's go with 0-50% as white, and 50%+ as green.  No need for red.

> Are bonus percentages always positive or can they go negative?

Always positive.

> should the client cache that planet's data 

No caching.

> Should we display an inner loader for this component while the data for the planet is being fetched from the API?

Yes, please!

**Comment by bpkennedy** [comment]
A couple more questions:

- [ ]  Since we are letting this be a reusable component - when the area of the component is too small and the content overflows and needs to scroll (say we need to scroll down) should we make the Title area remain fixed and the content scroll under it?  Or should the Title act as part of the same area as the content and it all scroll together (i.e. title would scroll up out of view)?
- [ ] On the page view of the planet - Does there need to be an outer border around the component (kinda like how the current IC frontend looks on the planet page)?  Or can I simply allow the component to fill 100% of the width/height of the page area?

**Comment by foohonpie** [comment]
> should we make the Title area remain fixed and the content scroll under it?

Yeah, let's go with a fixed title area.

> Does there need to be an outer border around the component

No outer-border necessary.

> The current design on the IC site - should that remain the same? Dark color background with opacity? Lighter colored Title bar area? Same font colors? Or do you want me to try to use what Quasar would naturally do for this kind of thing and we see what that looks like?

Let's go for what Quasar does naturally; we can throw away the existing IC styles in general. The bigger goal is to retain the functionality, even if it ends up looking a little unfamiliar.  No need to make it configurable.

Thanks!

**Comment by foohonpie** [comment]
Looks good from #12, although I'm seeing an odd issue where the initial GET returns a 404, but still renders the page.

Any ideas what may be causing that? 🤔

**Comment by foohonpie** [comment]
All good, we had hit the caveat mentioned here:

https://router.vuejs.org/guide/essentials/history-mode.html

Fixed by adjusting our nginx config.  Everything here looks good. 👍
