### ISSUE TITLE
Auth user can view Empire HQ from /hq

### ISSUE THREAD

**Issue by foohonpie** [ImperialConflict/imperialconflict.com#17]
## API

authenticate with the following user:

- email: `foo@bar.baz`
- password: `foobarbaz`

Then, with auth token, visit:

`GET /empire/388885 `

Note the singular `empire`, not `empires`.

Sample Response:

```
{
    "data": {
        "id": 388885,
        "name": "FoohonPie",
        "leader": "Ilikepie",
        "avatar_url": null,
        "family": {
            "id": 7143
        },
        "galaxy": {
            "name": "Virgo 2",
            "description": "The <b>training galaxy</b> where all beginners start their quest for glory. When you have managed to aquire <b>10 planets</b> here, you can play in the other galaxies. Use this training period wisely to stand a better chance later.",
            "map_image_path": "/images/Galaxies/Virgo 2.overview.jpg",
            "turn": 8858
        },
        "resources": {
            "gold": 2432389,
            "food": 0,
            "iron": 199,
            "octarine": 199,
            "endurium": 199
        },
        "morale": "110.0",
        "networth": 1250,
        "population": 10000,
        "planets_count": 1,
        "race": {
            "id": 618457,
            "name": "Knockout Foohons"
        }
    }
}
```

## Design

For now, just a simple card:

<img width="356" alt="Screen Shot 2020-12-09 at 5 57 22 PM" src="https://user-images.githubusercontent.com/674157/101711252-16d44b00-3a48-11eb-93cc-cbf014e0c613.png">

Notes:
* The "Race" link (Knockout Foohons in the example) can be a placeholder for now.
* Can ignore the resource growth/loss numbers in parentheses
* We can ignore images for now, as we don't yet have a plan for handling image assets in general.
* Order of resources (first 5 items) is: Gold, Food, Iron, Octarine, Endurium

---

Please let me know if there are any questions!

**Comment by foohonpie** [comment]
A note on the flow:

The site url `/hq` won't have any empire id within it.  That will come from the `/gate` page when a user selects which empire they want to play as.

I presume we'll want to keep their active empire id stored locally, and then grab it as needed for the API calls that require it.

**Comment by foohonpie** [comment]
Adding notes here per recent discussion:

There was a question of whether or not handling the "current empire" should be the concern of the FE or the BE.  We're deciding for now to keep it out of the BE to keep the API as close to RESTful as possible; meaning we want to keep unaware of client context.

So, when a user is on /gate, they can click on one of their active empires which should then store a "current empire id" value somewhere within the client (localStorage?) which will then use it as described above for API calls that require it.

We will stay aware of whether or not this causes trouble for the FE, and if necessary change /gate to PATCH the User instead such that subsequent calls return this from the BE.

**Comment by bpkennedy** [comment]
Questions!
 - [ ] Can I also add a the "Switch Empire" link to a navigation area, temporarily?  This will allow me to better test actually loading and unloading the "current empire" for real.  For now, I could just have that link drop any "current empire id", any current empire data, and return the user to the /gate view?
 - [ ] Should I include the number display filtering that is shown for resources on mobile?  (i.e. 34,000 vs 34k). Should be pretty straightforward to implement.  And if so, while abbreviateing "k" for thousands do you want me to add "m" for millions (1m instead of 1000k)?
 - [ ] I notice the morale value is a decimal.  Should I round to nearest whole percentage point?  Do I round up, down, or closest?
 - [ ] race, empire name, and empire leader are all user-entered strings.  If they are very long and the text is going to overflow their line - should the text ellipsize or wrap?

**Comment by foohonpie** [comment]
> Just to double check here - when this story is done the user should be able to go to /gate, see active empires, click on one of them to "Enter" and be routed to /hq view where they see this card?

Yep, that's correct!

> Can I also add a the "Switch Empire" link to a navigation area, temporarily? This will allow me to better test actually loading and unloading the "current empire" for real. For now, I could just have that link drop any "current empire id", any current empire data, and return the user to the /gate view?

That would be great. 👍

> Should I include the number display filtering that is shown for resources on mobile? (i.e. 34,000 vs 34k). Should be pretty straightforward to implement. And if so, while abbreviateing "k" for thousands do you want me to add "m" for millions (1m instead of 1000k)?

Yes please!

> I notice the morale value is a decimal. Should I round to nearest whole percentage point? Do I round up, down, or closest?

Let's round down to nearest whole percentage point.

> race, empire name, and empire leader are all user-entered strings. If they are very long and the text is going to overflow their line - should the text ellipsize or wrap?

Let's go with wrap and see if it presents issues.

> If a user has no auth token and they directly load the /hq route - should we redirect them to the login?

This sounds good.

> If a user has auth but does not have current empire id and they directly load the /hq route - should we show it empty or should we redirect them to /gate?

Redirect to gate sounds good.

> And for a rare edge case, if the user has no auth token but they do have a current empire id and they load /hq directly - we should also redirect them to login, yes?

Great question.  Yeah, this case should send em to login.
