### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by foohonpie** [ImperialConflict/imperialconflict.com#2]
<img width="1066" alt="Screen Shot 2020-11-11 at 11 24 06 AM" src="https://user-images.githubusercontent.com/674157/98855210-7cfd8c00-2410-11eb-9b49-38dae66904d3.png">

Please ignore the styles here; let's use the default Quasar stylings for the fonts and buttons.

For now, the buttons can be placeholder while I get the API docs up for reg/auth.

We can wipe the existing home page entirely, we don't need anything that is currently there.

**Comment by bpkennedy** [comment]
As discussed, let's get these in here first (and can happen on this story):

1. Use package.json rule to disable/prevent use of npm install in favor of yarn install.
2. Add ‘dev’, ‘build’, ‘serve’, ‘lint’, ‘test:e2e’, ‘test:e2e:ci’ npm tasks to package.json ‘scripts’
3. gitignore IDE specific configurations (.vscode, .quasar, .webstorm, etc…) and remove from repo.
4. Unify .eslintrc.js rules to be the same between pbbg.com and imperialconflict.com 
5. Add CONTRIBUTING.md and update README.md with it
